services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2025.5.2
    restart: on-failure
    network_mode: host
    environment:
      - TZ=Europe/Helsinki

